appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: d/NxoTdluJ6lilkXqG5r8ua85E7ba0l4ol9WA4E+IPTawWi5Xc3nDukKfpuucfJd/g9QGztDX6l8HjiCgP2QzrurhftlMLKJFzw/u4UrtAV+0HqPQNle2fV7Knh2lbzrTYb4CI2J31gDEhgiEUWVYTCgakUcecDQrOBmgRt6Hnk6yjhspZ9rVOT1TrqRA2eVwornB2csjgQ8mDC1MyEONV+dLrVEeiLGYITWGaW5LpUHbKvVgOHSe+Z6RunPaQOSbxK1QRg5oKmli6XJvLR8WvTSeXXUlOvwGBUIPiF+UA5hs82NzFQ/Uk4cpgb9bFz5wsjOpGI1nkkaesTh+cK30CP4iAGXrs0SKZzHJC1h1G7ku7j5jTrTnZxGy1w5JaDHyVYz7aAdftL0Ss58Pnqa0t6WB7GFM0D6EYkAHcgtyAP8/v/NEsJoaI0fXRbx0hGv/CVBiKM/x2/gW23f90MgG1JFrDmTbXMW1v7JTDUqmuRo9guvYYkoWDaxraMCD0ORjmHKZD9Cl+HMkoEkHDh+36r1ve3+Gn+XdE8AA2GjEv5bf6E1sjnTdYnM4aaNOWdmXScV9ZgMwXQ9c2yJJfAJr5Ry48F5lK3IkiyJfnciPEEnrlHRPrsoANjWS+U+WE5rL2lK0NwaY+vsRn77+W1xWcRmPW2UtPFtlo0nox9sIEI=}
